### ISSUE TITLE
Update rate setting gone

### ISSUE THREAD

**Issue by Bgagger** [satanasov/activenotifications#18]
Just noticed that after upgrading our boards to phpBB 3.3.0 the setting previously found under:
ACP -> Board features -> Active Notifications
To set how often the notifications should update is no longer there in the ACP. It used to be on the bottom. Now I can't find it anywhere.
The extension itself seems to be working as usual otherwise.

Can I find and manually alter this setting somewhere in the db?

Our community really likes this extension, it is a crucial feature for us. So thank you for making it :)

**Comment by kasimi** [comment]
See here: #19 After applying this change the setting will be back.

**Comment by Bgagger** [comment]
Wow, that was quick! Patch tested and works just fine. Thanks :)
